name: my_supabase
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  args: ^2.3.1
  shelf: ^1.3.1
  shelf_router: ^1.1.3
  supabase: ^0.3.4+1
  build_runner: ^2.1.11
  build_web_compilers: ^3.2.3
  encrypt: ^5.0.1

dev_dependencies:
  http: ^0.13.4
  lints: ^2.0.0
  test: ^1.21.2
